//  will be replaced by data from the server in the future

export default [
  {
    'id': 1,
    'row': 0,
    'col': 2,
    'coordinateX': 0,
    'coordinateY': 2
  }, {
    'id': 2,
    'row': 0,
    'col': 3,
    'coordinateX': 0,
    'coordinateY': 3
  }, {
    'id': 3,
    'row': 0,
    'col': 4,
    'coordinateX': 0,
    'coordinateY': 4
  }, {
    'id': 4,
    'row': 0,
    'col': 5,
    'coordinateX': 0,
    'coordinateY': 5
  }, {
    'id': 5,
    'row': 0,
    'col': 6,
    'coordinateX': 0,
    'coordinateY': 6
  }, {
    'id': 6,
    'row': 0,
    'col': 7,
    'coordinateX': 0,
    'coordinateY': 7
  }, {
    'id': 7,
    'row': 1,
    'col': 2,
    'coordinateX': 1,
    'coordinateY': 2
  }, {
    'id': 8,
    'row': 1,
    'col': 3,
    'coordinateX': 1,
    'coordinateY': 3
  }, {
    'id': 9,
    'row': 1,
    'col': 4,
    'coordinateX': 1,
    'coordinateY': 4
  }, {
    'id': 10,
    'row': 1,
    'col': 5,
    'coordinateX': 1,
    'coordinateY': 5
  }, {
    'id': 11,
    'row': 1,
    'col': 6,
    'coordinateX': 1,
    'coordinateY': 6
  }, {
    'id': 12,
    'row': 1,
    'col': 7,
    'coordinateX': 1,
    'coordinateY': 7
  }, {
    'id': 13,
    'row': 2,
    'col': 2,
    'coordinateX': 2,
    'coordinateY': 2
  }, {
    'id': 14,
    'row': 2,
    'col': 3,
    'coordinateX': 2,
    'coordinateY': 3
  }, {
    'id': 15,
    'row': 2,
    'col': 4,
    'coordinateX': 2,
    'coordinateY': 4
  }, {
    'id': 16,
    'row': 2,
    'col': 5,
    'coordinateX': 2,
    'coordinateY': 5
  }, {
    'id': 17,
    'row': 2,
    'col': 6,
    'coordinateX': 2,
    'coordinateY': 6
  }, {
    'id': 18,
    'row': 2,
    'col': 7,
    'coordinateX': 2,
    'coordinateY': 7
  }, {
    'id': 19,
    'row': 3,
    'col': 2,
    'coordinateX': 3,
    'coordinateY': 2
  }, {
    'id': 20,
    'row': 3,
    'col': 3,
    'coordinateX': 3,
    'coordinateY': 3
  }, {
    'id': 21,
    'row': 3,
    'col': 4,
    'coordinateX': 3,
    'coordinateY': 4
  }, {
    'id': 22,
    'row': 3,
    'col': 5,
    'coordinateX': 3,
    'coordinateY': 5
  }, {
    'id': 23,
    'row': 3,
    'col': 6,
    'coordinateX': 3,
    'coordinateY': 6
  }, {
    'id': 24,
    'row': 3,
    'col': 7,
    'coordinateX': 3,
    'coordinateY': 7
  }, {
    'id': 25,
    'row': 4,
    'col': 0,
    'coordinateX': 4,
    'coordinateY': 0
  }, {
    'id': 26,
    'row': 4,
    'col': 1,
    'coordinateX': 4,
    'coordinateY': 1
  }, {
    'id': 27,
    'row': 4,
    'col': 2,
    'coordinateX': 4,
    'coordinateY': 2
  }, {
    'id': 28,
    'row': 4,
    'col': 3,
    'coordinateX': 4,
    'coordinateY': 3
  }, {
    'id': 29,
    'row': 4,
    'col': 4,
    'coordinateX': 4,
    'coordinateY': 4
  }, {
    'id': 30,
    'row': 4,
    'col': 5,
    'coordinateX': 4,
    'coordinateY': 5
  }, {
    'id': 31,
    'row': 4,
    'col': 6,
    'coordinateX': 4,
    'coordinateY': 6
  }, {
    'id': 32,
    'row': 4,
    'col': 7,
    'coordinateX': 4,
    'coordinateY': 7
  }, {
    'id': 33,
    'row': 4,
    'col': 8,
    'coordinateX': 4,
    'coordinateY': 8
  }, {
    'id': 34,
    'row': 4,
    'col': 9,
    'coordinateX': 4,
    'coordinateY': 9
  }, {
    'id': 35,
    'row': 5,
    'col': 0,
    'coordinateX': 5,
    'coordinateY': 0
  }, {
    'id': 36,
    'row': 5,
    'col': 1,
    'coordinateX': 5,
    'coordinateY': 1
  }, {
    'id': 37,
    'row': 5,
    'col': 2,
    'coordinateX': 5,
    'coordinateY': 2
  }, {
    'id': 38,
    'row': 5,
    'col': 3,
    'coordinateX': 5,
    'coordinateY': 3
  }, {
    'id': 39,
    'row': 5,
    'col': 4,
    'coordinateX': 5,
    'coordinateY': 4
  }, {
    'id': 40,
    'row': 5,
    'col': 5,
    'coordinateX': 5,
    'coordinateY': 5
  }, {
    'id': 41,
    'row': 5,
    'col': 6,
    'coordinateX': 5,
    'coordinateY': 6
  }, {
    'id': 42,
    'row': 5,
    'col': 7,
    'coordinateX': 5,
    'coordinateY': 7
  }, {
    'id': 43,
    'row': 5,
    'col': 8,
    'coordinateX': 5,
    'coordinateY': 8
  }, {
    'id': 44,
    'row': 5,
    'col': 9,
    'coordinateX': 5,
    'coordinateY': 9
  }, {
    'id': 45,
    'row': 6,
    'col': 0,
    'coordinateX': 6,
    'coordinateY': 0
  }, {
    'id': 46,
    'row': 6,
    'col': 1,
    'coordinateX': 6,
    'coordinateY': 1
  }, {
    'id': 47,
    'row': 6,
    'col': 2,
    'coordinateX': 6,
    'coordinateY': 2
  }, {
    'id': 48,
    'row': 6,
    'col': 3,
    'coordinateX': 6,
    'coordinateY': 3
  }, {
    'id': 49,
    'row': 6,
    'col': 4,
    'coordinateX': 6,
    'coordinateY': 4
  }, {
    'id': 50,
    'row': 6,
    'col': 5,
    'coordinateX': 6,
    'coordinateY': 5
  }, {
    'id': 51,
    'row': 6,
    'col': 6,
    'coordinateX': 6,
    'coordinateY': 6
  }, {
    'id': 52,
    'row': 6,
    'col': 7,
    'coordinateX': 6,
    'coordinateY': 7
  }, {
    'id': 53,
    'row': 6,
    'col': 8,
    'coordinateX': 6,
    'coordinateY': 8
  }, {
    'id': 54,
    'row': 6,
    'col': 9,
    'coordinateX': 6,
    'coordinateY': 9
  }, {
    'id': 55,
    'row': 7,
    'col': 0,
    'coordinateX': 7,
    'coordinateY': 0
  }, {
    'id': 56,
    'row': 7,
    'col': 1,
    'coordinateX': 7,
    'coordinateY': 1
  }, {
    'id': 57,
    'row': 7,
    'col': 2,
    'coordinateX': 7,
    'coordinateY': 2
  }, {
    'id': 58,
    'row': 7,
    'col': 3,
    'coordinateX': 7,
    'coordinateY': 3
  }, {
    'id': 59,
    'row': 7,
    'col': 4,
    'coordinateX': 7,
    'coordinateY': 4
  }, {
    'id': 60,
    'row': 7,
    'col': 5,
    'coordinateX': 7,
    'coordinateY': 5
  }, {
    'id': 61,
    'row': 7,
    'col': 6,
    'coordinateX': 7,
    'coordinateY': 6
  }, {
    'id': 62,
    'row': 7,
    'col': 7,
    'coordinateX': 7,
    'coordinateY': 7
  }, {
    'id': 63,
    'row': 7,
    'col': 8,
    'coordinateX': 7,
    'coordinateY': 8
  }, {
    'id': 64,
    'row': 7,
    'col': 9,
    'coordinateX': 7,
    'coordinateY': 9
  }, {
    'id': 65,
    'row': 8,
    'col': 0,
    'coordinateX': 8,
    'coordinateY': 0
  }, {
    'id': 66,
    'row': 8,
    'col': 1,
    'coordinateX': 8,
    'coordinateY': 1
  }, {
    'id': 67,
    'row': 8,
    'col': 2,
    'coordinateX': 8,
    'coordinateY': 2
  }, {
    'id': 68,
    'row': 8,
    'col': 3,
    'coordinateX': 8,
    'coordinateY': 3
  }, {
    'id': 69,
    'row': 8,
    'col': 4,
    'coordinateX': 8,
    'coordinateY': 4
  }, {
    'id': 70,
    'row': 8,
    'col': 5,
    'coordinateX': 8,
    'coordinateY': 5
  }, {
    'id': 71,
    'row': 8,
    'col': 6,
    'coordinateX': 8,
    'coordinateY': 6
  }, {
    'id': 72,
    'row': 8,
    'col': 7,
    'coordinateX': 8,
    'coordinateY': 7
  }, {
    'id': 73,
    'row': 8,
    'col': 8,
    'coordinateX': 8,
    'coordinateY': 8
  }, {
    'id': 74,
    'row': 8,
    'col': 9,
    'coordinateX': 8,
    'coordinateY': 9
  }, {
    'id': 75,
    'row': 9,
    'col': 0,
    'coordinateX': 9,
    'coordinateY': 0
  }, {
    'id': 76,
    'row': 9,
    'col': 1,
    'coordinateX': 9,
    'coordinateY': 1
  }, {
    'id': 77,
    'row': 9,
    'col': 2,
    'coordinateX': 9,
    'coordinateY': 2
  }, {
    'id': 78,
    'row': 9,
    'col': 3,
    'coordinateX': 9,
    'coordinateY': 3
  }, {
    'id': 79,
    'row': 9,
    'col': 4,
    'coordinateX': 9,
    'coordinateY': 4
  }, {
    'id': 80,
    'row': 9,
    'col': 5,
    'coordinateX': 9,
    'coordinateY': 5
  }, {
    'id': 81,
    'row': 9,
    'col': 6,
    'coordinateX': 9,
    'coordinateY': 6
  }, {
    'id': 82,
    'row': 9,
    'col': 7,
    'coordinateX': 9,
    'coordinateY': 7
  }, {
    'id': 83,
    'row': 9,
    'col': 8,
    'coordinateX': 9,
    'coordinateY': 8
  }, {
    'id': 84,
    'row': 9,
    'col': 9,
    'coordinateX': 9,
    'coordinateY': 9
  }
]
