export default [{
  path: '/',
  name: 'home',
  component: require('@/pages/home')
}, {
  path: '/cinema-info',
  component: require('@/pages/cinema-info')
}, {
  path: '/movie-info',
  component: require('@/pages/movie-info')
}, {
  path: '/confirm-order',
  component: require('@/pages/confirm-order')
}, {
  path: '/profile',
  component: require('@/pages/profile')
}, {
  path: '/room-and-time',
  component: require('@/pages/room-and-time')
}, {
  path: '/seat-info',
  component: require('@/pages/seat-info')
}, {
  path: '/success',
  component: require('@/pages/success')
}, {
  path: '/trade-board',
  component: require('@/pages/trade-board')
}]
